---
engines:
  duplication:
    enabled: false  # Ignora si copiaste código parecido en dos archivos
  csslint:
    enabled: false  # Ignora errores de CSS
  eslint:
    enabled: false  # Ignora errores de JS
  phpmd:
    enabled: true
    configuration:
      rules:
        - "cleancode"
        - "codesize"
        - "controversial"
        - "design"
        - "naming"
      exclude:
        - "StaticAccess" # Permite usar métodos estáticos si los hay
        - "CyclomaticComplexity" # Ignora si tienes muchos 'if' (normal en HTML)
        - "NPathComplexity" 

exclude_paths:
  - "**/css/**"
  - "**/js/**"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/*_old.php"     # Ignora archivos que terminen en _old
  - "**/*_copia.php"   # Ignora copias
  - "**/test*.php"     # Ignora archivos de prueba
  - "**/vendor/**"     # Ignora librerías externas